# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GFSwifKlineDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    pod 'Alamofire'
    pod 'RxSwift',    '~> 4.0'
    pod 'RxCocoa',    '~> 4.0'
    pod 'SwiftyJSON'
    pod 'SnapKit'
    pod 'XCGLogger', '~> 6.1.0'

  # Pods for GFSwifKlineDemo

end
